---
title: "Corona Virus Report"
author:
- familyname: xxx
  othernames: xxx
  address: xxx
  email: xxx
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: Liang
  othernames: Xuanming
  address: Monash Universtidy
  email: xlia0003@student.monash.edu
  correspondingauthor: true
  qualifications:  Master
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(ggplot2)
```



\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}

\section*{Country XX3 and YY3}
```{r}
dat <- read.csv("Data/worldwidecases.csv")
```

```{r}
dat1 <- dat %>%
  filter(countriesAndTerritories == "India" | countriesAndTerritories == "Japan") %>%
  rename(countries = "countriesAndTerritories")
dat1
```

```{r}
dat2 <- dat1 %>% 
  group_by(countries) %>%
  summarise(cases = sum(cases))
dat2
dat3 <- dat1 %>%
  group_by(countries) %>%
  summarise(deaths = sum(deaths))
dat4 <- full_join(dat2, dat3)
kable(dat4)
```

```{r}
ggplot(dat4, aes(x =deaths,
                 fill = countries)) +
  geom_bar()
ggplot(dat4, aes(x = cases,
                 fill = countries)) +
  geom_bar()
```
\section*{country xx4 and YY4}



